'use strict';
const $=id=>document.getElementById(id);
const projectPresets={
 data:{label:'Data center / compute',power:45,water:.28,waste:.18,gas:10,fiber:3,redundancy:3},
 manufacturing:{label:'Advanced manufacturing',power:18,water:.75,waste:.58,gas:165,fiber:2,redundancy:2},
 semiconductor:{label:'Semiconductor / high-spec fab',power:62,water:2.2,waste:1.55,gas:140,fiber:3,redundancy:3},
 food:{label:'Food / beverage processing',power:7,water:1.4,waste:1.15,gas:120,fiber:1,redundancy:1},
 cold:{label:'Cold storage',power:9,water:.08,waste:.04,gas:35,fiber:1,redundancy:1},
 battery:{label:'Battery / energy manufacturing',power:28,water:.52,waste:.36,gas:90,fiber:2,redundancy:2},
 warehouse:{label:'Distribution / warehouse',power:3.5,water:.04,waste:.03,gas:18,fiber:1,redundancy:1},
 custom:{label:'Custom industrial load',power:10,water:.3,waste:.2,gas:50,fiber:1,redundancy:1}
};
const sites=[
{id:'GG-IL-101',name:'Joliet South',county:'Will County',state:'IL',power:58,water:2.6,waste:1.8,gas:260,fiber:3,lead:14,evidence:'Verified',confidence:92,redundancy:3,updated:'06 Sep 2026',change:'Power +7 MW',note:'Strong all-around heavy industrial profile with above-pilot power headroom.'},
{id:'GG-IL-102',name:'Elwood Logistics Belt',county:'Will County',state:'IL',power:22,water:1.1,waste:.74,gas:180,fiber:3,lead:11,evidence:'Reported',confidence:84,redundancy:2,updated:'03 Sep 2026',change:'Waste review',note:'Balanced logistics/manufacturing node; wastewater becomes limiting for wet-process uses.'},
{id:'GG-IL-103',name:'Rockford East',county:'Winnebago County',state:'IL',power:34,water:3.2,waste:2.4,gas:205,fiber:2,lead:18,evidence:'Verified',confidence:90,redundancy:2,updated:'30 Aug 2026',change:'No material change',note:'High water and wastewater headroom; moderate power lead time.'},
{id:'GG-IL-104',name:'Decatur Industrial Core',county:'Macon County',state:'IL',power:41,water:4.5,waste:3.1,gas:340,fiber:2,lead:20,evidence:'Reported',confidence:86,redundancy:2,updated:'28 Aug 2026',change:'Gas milestone',note:'Deep process-utility profile with timing risk on larger electric loads.'},
{id:'GG-IL-105',name:'Aurora West',county:'Kane County',state:'IL',power:17,water:1.5,waste:1.05,gas:135,fiber:3,lead:9,evidence:'Verified',confidence:93,redundancy:2,updated:'01 Sep 2026',change:'Fiber verified',note:'Fast-to-serve, fiber-rich node best suited to medium-load projects.'},
{id:'GG-IL-106',name:'Kankakee North',county:'Kankakee County',state:'IL',power:26,water:2.1,waste:1.2,gas:220,fiber:2,lead:16,evidence:'Modeled',confidence:69,redundancy:1,updated:'27 Aug 2026',change:'Model refreshed',note:'Promising modeled headroom but requires higher verification effort.'},
{id:'GG-IN-201',name:'Burns Harbor West',county:'Porter County',state:'IN',power:63,water:3.6,waste:2.0,gas:390,fiber:3,lead:17,evidence:'Reported',confidence:88,redundancy:3,updated:'05 Sep 2026',change:'Gas + future',note:'High-capacity industrial cluster with strong multi-system depth.'},
{id:'GG-IN-202',name:'Gary South',county:'Lake County',state:'IN',power:49,water:2.8,waste:1.35,gas:310,fiber:3,lead:15,evidence:'Reported',confidence:82,redundancy:3,updated:'02 Sep 2026',change:'Waste −0.6 MGD',note:'Large-load potential; wastewater collection is the key diligence item.'},
{id:'GG-IN-203',name:'South Bend Tech Belt',county:'St. Joseph County',state:'IN',power:31,water:1.3,waste:.92,gas:155,fiber:3,lead:12,evidence:'Verified',confidence:91,redundancy:2,updated:'29 Aug 2026',change:'Fiber confidence ↑',note:'Connectivity-led profile with solid power and moderate process capacity.'},
{id:'GG-IN-204',name:'Fort Wayne North',county:'Allen County',state:'IN',power:38,water:2.4,waste:1.7,gas:245,fiber:2,lead:13,evidence:'Verified',confidence:94,redundancy:2,updated:'01 Sep 2026',change:'No material change',note:'Consistent capacity across systems and strong evidence quality.'},
{id:'GG-IN-205',name:'Lafayette East',county:'Tippecanoe County',state:'IN',power:24,water:1.9,waste:1.45,gas:170,fiber:2,lead:10,evidence:'Reported',confidence:85,redundancy:2,updated:'26 Aug 2026',change:'Lead time −2 mo',note:'Good timing and water profile; larger electric projects need alternatives.'},
{id:'GG-IN-206',name:'Evansville North',county:'Vanderburgh County',state:'IN',power:29,water:3.8,waste:2.75,gas:280,fiber:2,lead:19,evidence:'Modeled',confidence:72,redundancy:1,updated:'24 Aug 2026',change:'Model refreshed',note:'High process-utility potential with evidence and timing still to prove.'}
];
const changes=[
{type:'POWER',date:'06 SEP 2026',title:'Substation headroom revised upward',text:'A newer planning record lifts usable capacity at the Joliet South pilot node and improves the fit for higher-load manufacturing.',delta:'+7 MW'},
{type:'WASTEWATER',date:'04 SEP 2026',title:'Collection constraint added',text:'Treatment headroom stayed flat, but a modeled collection bottleneck reduced near-term usable flow at one Indiana node.',delta:'−0.6 MGD'},
{type:'FIBER',date:'02 SEP 2026',title:'Second route moves to reported',text:'A previously modeled redundant path gained stronger evidence, reducing mission-critical connectivity risk.',delta:'↑ CONF.'},
{type:'GAS',date:'31 AUG 2026',title:'Reinforcement milestone advances',text:'A planned system reinforcement moved to permitted status, improving future capacity confidence but not current serviceability.',delta:'2028'}
];
let compareIds=JSON.parse(localStorage.getItem('gagegrid-compare')||'[]').filter(id=>sites.some(s=>s.id===id)).slice(0,3);
let lastAnalysis=null;
let lastRanking=[];
let toastTimer;
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]))}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function evidenceFactor(e,risk){const table={conservative:{Verified:1,Reported:.8,Modeled:.52},balanced:{Verified:1,Reported:.9,Modeled:.7},exploratory:{Verified:1,Reported:.96,Modeled:.86}};return table[risk][e]}
function evidenceUncertainty(e,confidence){const base={Verified:.05,Reported:.12,Modeled:.22}[e];return clamp(base+(100-confidence)/300,.04,.32)}
function siteBaseScore(s){const ev={Verified:1,Reported:.9,Modeled:.72}[s.evidence];const utility=Math.min(1,s.power/45)*.30+Math.min(1,s.water/2.5)*.15+Math.min(1,s.waste/1.7)*.15+Math.min(1,s.gas/280)*.17+Math.min(1,s.fiber/3)*.08+Math.min(1,s.redundancy/3)*.07;const timing=Math.max(.35,1-s.lead/50)*.08;return Math.round((utility+timing)*ev*100)}
function currentReq(){return{power:+$('powerReq').value||0,water:+$('waterReq').value||0,waste:+$('wasteReq').value||0,gas:+$('gasReq').value||0,fiber:+$('fiberReq').value||1,redundancy:+$('powerRedundancy').value||1,growth:(+$('growth').value||0)/100,timeline:+$('timeline').value||24,risk:$('risk').value,capital:+$('capitalExposure').value||0,projectType:$('projectType').value}}
function effectiveNeeds(req,stress=false){const growth=stress?req.growth+.25:req.growth;const timeline=stress?Math.max(12,req.timeline-12):req.timeline;return{power:req.power*(1+growth),water:req.water*(1+growth*.6),waste:req.waste*(1+growth*.6),gas:req.gas*(1+growth*.45),fiber:req.fiber,redundancy:req.redundancy,timeline}}
function requirementRows(s,req,stress=false){const needs=effectiveNeeds(req,stress);let risk=req.risk;if(stress&&risk==='exploratory')risk='balanced';else if(stress&&risk==='balanced')risk='conservative';const ef=evidenceFactor(s.evidence,risk);const values=[['Power',s.power,needs.power,'MW'],['Water',s.water,needs.water,'MGD'],['Wastewater',s.waste,needs.waste,'MGD'],['Gas',s.gas,needs.gas,'MMBtu/h'],['Fiber',s.fiber,needs.fiber,'routes'],['Power redundancy',s.redundancy,needs.redundancy,'level']];return values.map(([name,raw,need,unit])=>{const usable=raw*ef;const ratio=need===0?3:usable/need;return{name,raw,usable,need,unit,ratio,gap:usable-need}})}
function analyzeSite(s,req,stress=false){const rows=requirementRows(s,req,stress);const needs=effectiveNeeds(req,stress);const worst=[...rows].sort((a,b)=>a.ratio-b.ratio)[0];const coverage=Math.min(...rows.map(r=>Math.min(1.15,r.ratio)));const timingRatio=needs.timeline/s.lead;const risk=stress?(req.risk==='exploratory'?'balanced':req.risk==='balanced'?'conservative':'conservative'):req.risk;const ef=evidenceFactor(s.evidence,risk);let score=Math.round((Math.min(1,coverage)*.58+Math.min(1,timingRatio)*.17+ef*.11+(s.confidence/100)*.08+Math.min(1,s.redundancy/req.redundancy)*.06)*100);score=clamp(score,5,99);const uncertainty=evidenceUncertainty(s.evidence,s.confidence);const low=clamp(Math.round(score*(1-uncertainty)),1,99);const high=clamp(Math.round(score+(100-score)*(uncertainty*.7)),1,99);let verdict='GO TO DILIGENCE',vclass='go';if(worst.ratio<.8||timingRatio<.68){verdict='HOLD / RESCOPE';vclass='hold'}else if(worst.ratio<1.15||timingRatio<1||s.evidence==='Modeled'||low<70){verdict='CONDITIONAL';vclass='conditional'}const bufferPct=Math.round((worst.ratio-1)*100);const atRisk=verdict==='HOLD / RESCOPE'?req.capital:verdict==='CONDITIONAL'?req.capital*.45:req.capital*.15;return{s,req,stress,rows,worst,score,low,high,verdict,vclass,timingRatio,needs,bufferPct,atRisk}}
function format(v,type){if(type==='Power')return`${v.toFixed(1)} MW`;if(type==='Water'||type==='Wastewater')return`${v.toFixed(2)} MGD`;if(type==='Gas')return`${Math.round(v)} MMBtu/h`;if(type==='Fiber')return`${Math.round(v)} routes`;if(type==='Power redundancy')return`Level ${Math.round(v)}`;return String(v)}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v)}
function nextStep(worst,s){const steps={Power:'Request a preliminary utility load study and confirm substation, feeder and upgrade timing at the exact parcel.',Water:'Confirm firm source, storage and distribution capacity at the parcel—not only treatment-plant headroom.',Wastewater:'Verify collection-system capacity, discharge limits and pretreatment requirements before relying on treatment headroom.',Gas:'Request firm pressure/flow availability and reinforcement timing for the project load.',Fiber:'Confirm physically diverse routes and carrier ownership rather than counting nearby conduit.','Power redundancy':'Confirm independent feed paths, common points of failure and whether the required topology can be delivered.'};return `${steps[worst.name]} Current pilot evidence: ${s.evidence.toLowerCase()} (${s.confidence}% confidence).`}
function fixPath(a){const w=a.worst;if(w.ratio>=1)return`No capacity addition is indicated by the risk-adjusted pilot model. The decision is more sensitive to ${a.timingRatio<1?'delivery timing':'verification quality'} than raw headroom.`;const gap=Math.abs(w.gap);return `${w.name} needs approximately ${format(gap,w.name)} of additional risk-adjusted usable capacity, or the project requirement must fall by about ${Math.ceil((1-w.ratio)*100)}%, to reach 100% modeled coverage.`}
function diligenceSteps(a){const w=a.worst.name;const generic=['Confirm parcel falls inside the intended utility service territories.','Obtain written utility confirmation for the entered peak and growth case.','Re-run the screen when utility evidence changes; do not carry forward stale headroom.'];const special={Power:['Request load letter / preliminary service study.','Confirm feeder/substation topology and upgrade scope.','Validate energization date against equipment procurement.'],Water:['Confirm firm source and pressure at parcel.','Check storage and fire-flow requirements.','Validate allocation / drought or seasonal restrictions.'],Wastewater:['Confirm collection—not only treatment—capacity.','Check industrial discharge and pretreatment thresholds.','Validate lift station / trunk constraints.'],Gas:['Confirm firm flow and pressure.','Identify reinforcement scope and responsibility.','Check curtailment / interruptible-service assumptions.'],Fiber:['Map carrier ownership and physical route diversity.','Confirm lateral construction timing.','Verify SLA / redundancy requirements.'],'Power redundancy':['Confirm independent utility paths.','Identify shared substation / corridor failure modes.','Validate topology against project reliability requirement.']};return[...(special[w]||[]),...generic].slice(0,5)}
function persistScenarioToUrl(){const r=currentReq();const params=new URLSearchParams({p:r.projectType,s:$('siteSelect').value,pw:r.power,w:r.water,ww:r.waste,g:r.gas,f:r.fiber,rd:r.redundancy,t:r.timeline,r:r.risk,gr:Math.round(r.growth*100)});history.replaceState(null,'',`${location.pathname}?${params.toString()}${location.hash||''}`)}
function loadScenarioFromUrl(){const q=new URLSearchParams(location.search);if(!q.size)return false;const map={p:'projectType',s:'siteSelect',pw:'powerReq',w:'waterReq',ww:'wasteReq',g:'gasReq',f:'fiberReq',rd:'powerRedundancy',t:'timeline',r:'risk',gr:'growth'};Object.entries(map).forEach(([k,id])=>{if(q.has(k)&&$(id))$(id).value=q.get(k)});return q.has('s')}
function presetProject(){const p=projectPresets[$('projectType').value];$('powerReq').value=p.power;$('waterReq').value=p.water;$('wasteReq').value=p.waste;$('gasReq').value=p.gas;$('fiberReq').value=p.fiber;$('powerRedundancy').value=p.redundancy;updateRankSummary()}
function populateSiteSelect(){$('siteSelect').innerHTML=sites.map(s=>`<option value="${s.id}">${esc(s.name)} · ${s.state} · broad score ${siteBaseScore(s)}</option>`).join('')}
function updateRankSummary(){const r=currentReq(),p=projectPresets[r.projectType];$('rankProjectName').textContent=p?.label||'Custom project';$('rankProjectSummary').textContent=`${r.power} MW · ${r.water} MGD water · ${r.waste} MGD wastewater · ${r.gas} MMBtu/h gas · ${r.timeline} mo target · ${Math.round(r.growth*100)}% growth case`;}
function runAnalysis(){const s=sites.find(x=>x.id===$('siteSelect').value);const req=currentReq();const a=analyzeSite(s,req);const stress=analyzeSite(s,req,true);lastAnalysis=a;persistScenarioToUrl();updateRankSummary();const ready=`${s.lead}–${s.lead+6} mo`;const capRisk=a.verdict==='HOLD / RESCOPE'?'HIGH':a.verdict==='CONDITIONAL'?'MEDIUM':'LOW';const constraints=a.rows.map(r=>{const pct=Math.min(100,Math.round(r.ratio*100));const cls=r.ratio<1?'bad':r.ratio<1.25?'warn':'good';const status=r.ratio<1?'SHORTFALL':r.ratio<1.25?'TIGHT':'PASS';return`<div class="constraint ${cls}"><div class="constraint-head"><b>${r.name}</b><span>${status} · ${Math.round(r.ratio*100)}% coverage</span></div><div class="bar"><i style="width:${pct}%"></i></div><p>Risk-adjusted usable: ${format(r.usable,r.name)} · growth-adjusted need: ${format(r.need,r.name)} · raw pilot headroom: ${format(r.raw,r.name)}</p></div>`}).join('');const decisionFlip=stress.verdict!==a.verdict||stress.score<a.score-12;const diligence=diligenceSteps(a).map(x=>`<li>${esc(x)}</li>`).join('');
$('resultState').innerHTML=`<div class="result-top"><div class="score-ring" style="--scoredeg:${a.score*3.6}deg"><div class="score-inner"><b>${a.score}</b><span>FEASIBILITY</span><small>${a.low}–${a.high} RANGE</small></div></div><div><span class="verdict ${a.vclass}">${a.verdict}</span><h3>${esc(s.name)}</h3><p>${a.worst.name} is the limiting system. ${a.bufferPct>=0?`The risk-adjusted buffer is about ${a.bufferPct}% above the growth-adjusted requirement.`:`The project exceeds risk-adjusted usable ${a.worst.name.toLowerCase()} capacity by about ${Math.abs(a.bufferPct)}%.`} ${nextStep(a.worst,s)}</p></div></div>
<div class="result-grid"><div><small>PRIMARY BOTTLENECK</small><b>${a.worst.name}</b></div><div><small>CAPITAL-AT-RISK SIGNAL</small><b>${capRisk}${req.capital?` · ${money(a.atRisk)}`:''}</b></div><div><small>INDICATIVE READY WINDOW</small><b>${ready}</b></div><div><small>EVIDENCE / CONFIDENCE</small><b>${s.evidence} · ${s.confidence}%</b></div></div>
<div class="insight-grid"><article class="insight-card"><h4>What would make it work?</h4><p>${esc(fixPath(a))}</p></article><article class="insight-card"><h4>Stress case</h4><p><strong>${stress.score}/100 · ${stress.verdict}</strong><br>Tests +25 points of extra load growth, a 12-month faster target and stricter evidence treatment. ${decisionFlip?'The decision meaningfully deteriorates under stress.':'The decision remains directionally stable under stress.'}</p></article><article class="insight-card"><h4>Uncertainty range</h4><p><strong>${a.low}–${a.high}</strong><br>The range widens as evidence becomes more modeled and confidence falls. This is intended to prevent false precision from one score.</p></article><article class="insight-card"><h4>Residual optionality</h4><p>${a.rows.filter(r=>r.ratio>1).length} of ${a.rows.length} dependencies retain modeled headroom after the growth case. ${a.worst.ratio<1?'The current bottleneck blocks full optionality.':'No modeled shortfall is present in the base case.'}</p></article></div>
<div class="kicker">SYSTEM COVERAGE</div><div class="constraint-list">${constraints}</div>
<div class="diligence"><div class="kicker">ORDERED DILIGENCE PATH</div><ol>${diligence}</ol></div>
<div class="actions-row"><button class="smallbtn" id="saveBtn" type="button">SAVE DECISION</button><button class="smallbtn" id="compareBtn" type="button">ADD TO COMPARE</button><button class="smallbtn" id="shareBtn" type="button">COPY SCENARIO LINK</button><button class="smallbtn" id="exportBtn" type="button">EXPORT MEMO</button><button class="smallbtn" id="printBtn" type="button">PRINT / PDF</button><button class="smallbtn" id="openRecord" type="button">OPEN SITE RECORD</button></div>`;
$('emptyState').classList.add('hidden');$('resultState').classList.remove('hidden');$('saveBtn').onclick=()=>saveScreen(a);$('compareBtn').onclick=()=>addCompare(s.id);$('shareBtn').onclick=copyScenarioLink;$('exportBtn').onclick=()=>exportMemo(a,stress);$('printBtn').onclick=()=>window.print();$('openRecord').onclick=()=>openSiteDialog(s);updateSavedCount();}
function rankAll(){const req=currentReq();lastRanking=sites.map(s=>analyzeSite(s,req)).sort((a,b)=>b.score-a.score||b.low-a.low||a.s.lead-b.s.lead);renderRanking();updateRankSummary();$('ranking').scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderRanking(){if(!lastRanking.length){$('ranking').className='ranking empty-panel';$('ranking').innerHTML='<b>No ranking yet.</b><span>Use the project inputs above, then rank all 12 pilot nodes.</span>';return}$('ranking').className='ranking';$('ranking').innerHTML=lastRanking.map((a,i)=>`<div class="rank-row"><div class="rank-num">${String(i+1).padStart(2,'0')}</div><div class="rank-site"><b>${esc(a.s.name)}</b><span>${a.s.county}, ${a.s.state} · ${a.s.evidence} ${a.s.confidence}%</span><div class="fitbar"><i style="width:${a.score}%"></i></div></div><div class="rank-score">${a.score}<span style="display:block;font:8px var(--mono);color:var(--muted)">${a.low}–${a.high}</span></div><div class="rank-cell"><b>${a.verdict.replace('GO TO DILIGENCE','GO')}</b><span>VERDICT</span></div><div class="rank-cell"><b>${a.s.lead} mo</b><span>LEAD</span></div><div class="rank-cell"><b>${a.worst.name}</b><span>BOTTLENECK · ${Math.round(a.worst.ratio*100)}%</span></div><div class="rank-actions"><button class="smallbtn" data-open="${a.s.id}">OPEN</button><button class="smallbtn ${compareIds.includes(a.s.id)?'active':''}" data-compare="${a.s.id}">${compareIds.includes(a.s.id)?'ADDED':'COMPARE'}</button></div></div>`).join('');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{loadSite(b.dataset.open);runAnalysis();$('screen').scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>addCompare(b.dataset.compare))}
function addCompare(id){if(compareIds.includes(id)){toast('Site already in compare.');return}if(compareIds.length>=3){toast('Compare supports up to three sites.');return}compareIds.push(id);localStorage.setItem('gagegrid-compare',JSON.stringify(compareIds));renderComparison();renderRanking();renderPortfolio();toast('Added to comparison.');}
function removeCompare(id){compareIds=compareIds.filter(x=>x!==id);localStorage.setItem('gagegrid-compare',JSON.stringify(compareIds));renderComparison();renderRanking();renderPortfolio()}
function renderComparison(){if(!compareIds.length){$('comparison').className='comparison empty-panel';$('comparison').innerHTML='<b>No sites shortlisted.</b><span>Add up to three sites to compare them against the current project.</span>';$('compareHint').textContent='Choose “Compare” from a ranking or site card.';return}const req=currentReq();const arr=compareIds.map(id=>analyzeSite(sites.find(s=>s.id===id),req));$('compareHint').textContent=`Comparing ${arr.length} site${arr.length>1?'s':''} against ${projectPresets[req.projectType]?.label||'current project'}.`;$('comparison').className='comparison';const row=(label,fn,cls=()=>'',raw=false)=>`<div class="compare-label">${label}</div>${arr.map(a=>`<div class="compare-value ${cls(a)}">${raw?fn(a):esc(fn(a))}</div>`).join('')}`;let html=`<div class="compare-grid" style="--cols:${arr.length}"><div class="compare-label">SITE</div>${arr.map(a=>`<div class="compare-head"><b>${esc(a.s.name)}</b><span>${a.s.county}, ${a.s.state}<br>${a.s.evidence} · ${a.s.confidence}% confidence</span><button class="compare-remove" data-remove="${a.s.id}">REMOVE</button></div>`).join('')}`;html+=row('FEASIBILITY',a=>`${a.score}/100 · range ${a.low}–${a.high}`,a=>a.score>=80?'good':a.score>=65?'warn':'bad');html+=row('VERDICT',a=>a.verdict,a=>a.vclass==='go'?'good':a.vclass==='conditional'?'warn':'bad');html+=row('BOTTLENECK',a=>`${a.worst.name} · ${Math.round(a.worst.ratio*100)}%`,a=>a.worst.ratio>=1.25?'good':a.worst.ratio>=1?'warn':'bad');html+=row('READY / LEAD',a=>`${a.s.lead}–${a.s.lead+6} months`,a=>a.timingRatio>=1.2?'good':a.timingRatio>=1?'warn':'bad');html+=row('POWER BUFFER',a=>`${Math.round((a.rows[0].ratio-1)*100)}%`,a=>a.rows[0].ratio>=1.25?'good':a.rows[0].ratio>=1?'warn':'bad');html+=row('WATER BUFFER',a=>`${Math.round((a.rows[1].ratio-1)*100)}%`,a=>a.rows[1].ratio>=1.25?'good':a.rows[1].ratio>=1?'warn':'bad');html+=row('WASTEWATER BUFFER',a=>`${Math.round((a.rows[2].ratio-1)*100)}%`,a=>a.rows[2].ratio>=1.25?'good':a.rows[2].ratio>=1?'warn':'bad');html+=row('GAS BUFFER',a=>`${Math.round((a.rows[3].ratio-1)*100)}%`,a=>a.rows[3].ratio>=1.25?'good':a.rows[3].ratio>=1?'warn':'bad');html+=row('NEXT DILIGENCE',a=>nextStep(a.worst,a.s));html+='</div>';$('comparison').innerHTML=html;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeCompare(b.dataset.remove))}
function renderPortfolio(){const top=[...sites].sort((a,b)=>siteBaseScore(b)-siteBaseScore(a)).slice(0,6);$('portfolio').innerHTML=top.map((s,i)=>`<article class="site-card"><div class="meta"><span>#${String(i+1).padStart(2,'0')} BROAD RANK</span><span>${s.state}</span></div><h3>${esc(s.name)}</h3><p>${esc(s.note)}</p><div class="capacity-strip"><div><b>${s.power} MW</b><span>POWER</span></div><div><b>${s.water} MGD</b><span>WATER</span></div><div><b>${s.waste} MGD</b><span>WASTEWATER</span></div></div><div class="site-score"><span>${siteBaseScore(s)} / 100</span><i style="max-width:${siteBaseScore(s)}%"></i></div><div class="site-card-actions"><button class="smallbtn" data-screen="${s.id}">SCREEN</button><button class="smallbtn ${compareIds.includes(s.id)?'active':''}" data-cardcompare="${s.id}">${compareIds.includes(s.id)?'ADDED':'COMPARE'}</button></div></article>`).join('');document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{loadSite(b.dataset.screen);runAnalysis();$('screen').scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-cardcompare]').forEach(b=>b.onclick=()=>addCompare(b.dataset.cardcompare))}
function records(){const out=[];for(const s of sites){const vals=[['Power',s.power,'MW'],['Water',s.water,'MGD'],['Wastewater',s.waste,'MGD'],['Gas',s.gas,'MMBtu/h'],['Fiber',s.fiber,'routes']];vals.forEach(([type,val,unit],i)=>out.push({id:`${s.id}-${String(i+1).padStart(2,'0')}`,site:s.name,county:s.county,state:s.state,type,val,unit,evidence:s.evidence,confidence:Math.max(55,s.confidence-(i%3)*3),lead:Math.max(6,s.lead+(i-2)*2),updated:s.updated,note:s.note}))}return out}
const registry=records();let filteredRegistry=registry;
function renderRegistry(){const q=$('regSearch').value.trim().toLowerCase(),r=$('region').value,t=$('type').value,e=$('evidence').value;filteredRegistry=registry.filter(x=>(r==='all'||x.state===r)&&(t==='all'||x.type===t)&&(e==='all'||x.evidence===e)&&(!q||`${x.id} ${x.site} ${x.county} ${x.state} ${x.type}`.toLowerCase().includes(q)));$('count').textContent=String(filteredRegistry.length).padStart(2,'0');$('registrySummary').textContent=`${filteredRegistry.length} of ${registry.length} records`;$('rows').innerHTML=filteredRegistry.map(x=>`<tr data-id="${x.id}"><td class="mono">${x.id}</td><td><b>${esc(x.site)}</b><br><span class="note">${esc(x.county)}</span></td><td class="mono">${x.state}</td><td>${x.type}</td><td class="headroom">${x.val} ${x.unit}</td><td><span class="pill ${x.evidence}">${x.evidence}</span></td><td class="mono">${x.confidence}%</td><td class="mono">${x.lead} mo</td><td class="mono">${x.updated}</td></tr>`).join('');document.querySelectorAll('#rows tr').forEach(tr=>tr.onclick=()=>openRecordDialog(registry.find(x=>x.id===tr.dataset.id)))}
function renderChanges(){$('changeGrid').innerHTML=changes.map(c=>`<article><div class="meta"><span>${c.type}</span><span>${c.date}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p><div class="delta">${c.delta}</div></article>`).join('')}
function renderMatrix(){const top=[...sites].sort((a,b)=>siteBaseScore(b)-siteBaseScore(a)).slice(0,5);const heads=['','POWER','WATER','WASTE','GAS','FIBER'];let html=heads.map(h=>`<div class="matrix-head">${h}</div>`).join('');top.forEach(s=>{html+=`<div class="label">${esc(s.name)}</div>`;const vals=[s.power/45,s.water/2.5,s.waste/1.7,s.gas/280,s.fiber/3];vals.forEach(v=>html+=`<div class="${v>=.9?'on':v>=.65?'mid':'off'}">${Math.round(v*100)}%</div>`)});$('matrix').innerHTML=html}
function loadSite(id){if(sites.some(s=>s.id===id))$('siteSelect').value=id}
function saveScreen(a){const saved=JSON.parse(localStorage.getItem('gagegrid-screens')||'[]');const item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),siteId:a.s.id,site:a.s.name,projectType:a.req.projectType,req:a.req,score:a.score,low:a.low,high:a.high,verdict:a.verdict,bottleneck:a.worst.name,date:new Date().toISOString()};saved.unshift(item);localStorage.setItem('gagegrid-screens',JSON.stringify(saved.slice(0,30)));renderSavedScreens();updateSavedCount();$('saveBtn').textContent='SAVED ✓';toast('Decision saved in this browser.')}
function updateSavedCount(){const saved=JSON.parse(localStorage.getItem('gagegrid-screens')||'[]');$('savedCount').textContent=saved.length}
function renderSavedScreens(){const saved=JSON.parse(localStorage.getItem('gagegrid-screens')||'[]');if(!saved.length){$('savedScreens').className='saved-grid empty-panel';$('savedScreens').innerHTML='<b>No saved screens.</b><span>Save a feasibility result and it will appear here.</span>';return}$('savedScreens').className='saved-grid';$('savedScreens').innerHTML=saved.slice(0,9).map(x=>`<article class="saved-card"><div class="meta"><span>${new Date(x.date).toLocaleDateString()}</span><span>${x.score}/100</span></div><h3>${esc(x.site)}</h3><p>${esc(projectPresets[x.projectType]?.label||x.projectType)}<br>${esc(x.verdict)} · bottleneck ${esc(x.bottleneck)}<br>score range ${x.low}–${x.high}</p><div class="saved-card-actions"><button class="smallbtn" data-reopen="${x.id}">REOPEN</button><button class="smallbtn danger" data-delete="${x.id}">DELETE</button></div></article>`).join('');document.querySelectorAll('[data-reopen]').forEach(b=>b.onclick=()=>reopenSaved(b.dataset.reopen));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteSaved(b.dataset.delete))}
function reopenSaved(id){const saved=JSON.parse(localStorage.getItem('gagegrid-screens')||'[]');const x=saved.find(i=>i.id===id);if(!x)return;loadSite(x.siteId);$('projectType').value=x.projectType;const r=x.req;$('powerReq').value=r.power;$('waterReq').value=r.water;$('wasteReq').value=r.waste;$('gasReq').value=r.gas;$('fiberReq').value=r.fiber;$('powerRedundancy').value=r.redundancy;$('timeline').value=r.timeline;$('risk').value=r.risk;$('growth').value=Math.round((r.growth||0)*100);$('capitalExposure').value=r.capital||0;runAnalysis();$('screen').scrollIntoView({behavior:'smooth'})}
function deleteSaved(id){let saved=JSON.parse(localStorage.getItem('gagegrid-screens')||'[]');saved=saved.filter(x=>x.id!==id);localStorage.setItem('gagegrid-screens',JSON.stringify(saved));renderSavedScreens();updateSavedCount();toast('Saved decision deleted.')}
function openRecordDialog(x){$('modalContent').innerHTML=`<div class="kicker">CAPACITY RECORD / ${x.id}</div><h3>${esc(x.site)} — ${x.type}</h3><p>${esc(x.note)}</p><div class="stats"><div><small>USABLE PILOT HEADROOM</small><b>${x.val} ${x.unit}</b></div><div><small>EVIDENCE</small><b>${x.evidence}</b></div><div><small>CONFIDENCE</small><b>${x.confidence}%</b></div></div><div class="sources"><div><span>Location</span><span>${esc(x.county)}, ${x.state}</span></div><div><span>Indicative lead time</span><span>${x.lead} months</span></div><div><span>Updated</span><span>${x.updated}</span></div><div><span>Production lineage</span><span>Source URI · retrieval date · service territory · method · utility verification</span></div></div><p class="note">Simulated pilot data. Do not use as a service commitment or engineering determination.</p>`;$('recordDialog').showModal()}
function openSiteDialog(s){$('modalContent').innerHTML=`<div class="kicker">SITE NODE / ${s.id}</div><h3>${esc(s.name)}</h3><p>${esc(s.note)}</p><div class="stats"><div><small>BROAD SITE SCORE</small><b>${siteBaseScore(s)}/100</b></div><div><small>EVIDENCE</small><b>${s.evidence}</b></div><div><small>CONFIDENCE</small><b>${s.confidence}%</b></div></div><div class="sources"><div><span>Power</span><span>${s.power} MW · redundancy ${s.redundancy}/3</span></div><div><span>Water / wastewater</span><span>${s.water} / ${s.waste} MGD</span></div><div><span>Gas</span><span>${s.gas} MMBtu/h</span></div><div><span>Fiber</span><span>${s.fiber} route level</span></div><div><span>Indicative lead time</span><span>${s.lead} months</span></div><div><span>Latest tracked change</span><span>${esc(s.change)}</span></div></div>`;$('recordDialog').showModal()}
function downloadText(name,text,type='text/plain'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function exportRegistry(){const header=['Record','Site','County','State','System','Headroom','Unit','Evidence','Confidence','Lead months','Updated'];const lines=[header,...filteredRegistry.map(x=>[x.id,x.site,x.county,x.state,x.type,x.val,x.unit,x.evidence,x.confidence,x.lead,x.updated])].map(r=>r.map(csvCell).join(','));downloadText('gage-grid-registry.csv',lines.join('\n'),'text/csv')}
function exportRanking(){if(!lastRanking.length)rankAll();const header=['Rank','Site','County','State','Score','Low','High','Verdict','Bottleneck','Coverage %','Lead months','Evidence','Confidence'];const lines=[header,...lastRanking.map((a,i)=>[i+1,a.s.name,a.s.county,a.s.state,a.score,a.low,a.high,a.verdict,a.worst.name,Math.round(a.worst.ratio*100),a.s.lead,a.s.evidence,a.s.confidence])].map(r=>r.map(csvCell).join(','));downloadText('gage-grid-project-ranking.csv',lines.join('\n'),'text/csv')}
function exportMemo(a,stress){const r=a.req;const lines=[`GAGE GRID — SITE FEASIBILITY MEMO`,`Generated: ${new Date().toLocaleString()}`,`Simulation prototype — not an engineering determination`,``,`PROJECT`,projectPresets[r.projectType]?.label||r.projectType,`Growth assumption: ${Math.round(r.growth*100)}%`,`Target online: ${r.timeline} months`,`Risk posture: ${r.risk}`,``,`SITE`,`${a.s.name}, ${a.s.county}, ${a.s.state}`,`Evidence: ${a.s.evidence} (${a.s.confidence}% confidence)`,`Indicative infrastructure lead time: ${a.s.lead} months`,``,`DECISION`,`Feasibility: ${a.score}/100`,`Uncertainty range: ${a.low}-${a.high}`,`Verdict: ${a.verdict}`,`Primary bottleneck: ${a.worst.name}`,`Stress case: ${stress.score}/100 — ${stress.verdict}`,``,`WHAT WOULD MAKE IT WORK`,fixPath(a),``,`SYSTEM COVERAGE`,...a.rows.map(x=>`${x.name}: ${Math.round(x.ratio*100)}% risk-adjusted coverage | usable ${format(x.usable,x.name)} | need ${format(x.need,x.name)}`),``,`DILIGENCE ORDER`,...diligenceSteps(a).map((x,i)=>`${i+1}. ${x}`),``,`NEXT STEP`,nextStep(a.worst,a.s)];downloadText(`gage-grid-${a.s.id.toLowerCase()}-memo.txt`,lines.join('\n'))}
async function copyScenarioLink(){persistScenarioToUrl();try{await navigator.clipboard.writeText(location.href);toast('Scenario link copied.')}catch{toast('Scenario URL is in the address bar.')}}
function clearFilters(){$('regSearch').value='';$('region').value='all';$('type').value='all';$('evidence').value='all';renderRegistry()}
function loadDemo(){$('projectType').value='manufacturing';presetProject();$('siteSelect').value='GG-IL-102';$('timeline').value='24';$('risk').value='balanced';$('growth').value='25';runAnalysis();rankAll();if(!compareIds.includes('GG-IL-102'))addCompare('GG-IL-102');if(!compareIds.includes('GG-IN-204')&&compareIds.length<3)addCompare('GG-IN-204');$('screen').scrollIntoView({behavior:'smooth'})}
function bind(){
 $('projectType').addEventListener('change',presetProject);$('analyseBtn').addEventListener('click',runAnalysis);$('rankAllBtn').addEventListener('click',rankAll);$('exportRankBtn').addEventListener('click',exportRanking);$('clearCompareBtn').addEventListener('click',()=>{compareIds=[];localStorage.setItem('gagegrid-compare','[]');renderComparison();renderRanking();renderPortfolio()});$('exportRegistryBtn').addEventListener('click',exportRegistry);$('loadDemoBtn').addEventListener('click',loadDemo);
 ['powerReq','waterReq','wasteReq','gasReq','fiberReq','powerRedundancy','timeline','risk','growth'].forEach(id=>$(id).addEventListener('change',()=>{updateRankSummary();renderComparison()}));
 [$('regSearch'),$('region'),$('type'),$('evidence')].forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',renderRegistry));$('clear').onclick=clearFilters;$('closeDialog').onclick=()=>$('recordDialog').close();$('recordDialog').addEventListener('click',e=>{if(e.target===$('recordDialog'))$('recordDialog').close()});$('accessForm').addEventListener('submit',e=>{e.preventDefault();const val=$('email').value.trim();const leads=JSON.parse(localStorage.getItem('gagegrid-pilot-requests')||'[]');leads.push({email:val,date:new Date().toISOString()});localStorage.setItem('gagegrid-pilot-requests',JSON.stringify(leads));$('msg').textContent='Pilot request saved in this prototype. ✓';$('email').value=''});
}
function init(){populateSiteSelect();presetProject();const fromUrl=loadScenarioFromUrl();renderPortfolio();renderRegistry();renderChanges();renderMatrix();renderComparison();renderSavedScreens();updateSavedCount();$('metricRecords').textContent=registry.length;bind();if(fromUrl)runAnalysis()}
init();
