(() => {
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
  ready(()=>{
    const ribbon=document.querySelector('.ribbon');let networkNote=document.querySelector('[data-network-note]');if(!networkNote&&ribbon){networkNote=document.createElement('span');networkNote.dataset.networkNote='true';ribbon.appendChild(networkNote)}
    if(ribbon&&ribbon.firstChild?.nodeType===Node.TEXT_NODE)ribbon.firstChild.textContent='OPERATING PILOT · SIMULATED CAPACITY WHERE LABELED · LIVE PUBLIC EVIDENCE WHERE LABELED · UTILITY VERIFICATION REQUIRED';
    const savedCopy=document.querySelector('.saved-section .head>p');if(savedCopy)savedCopy.textContent='Saved screens stay in this browser for the operating pilot. Revisit a decision without rerunning the same analysis from scratch.';
    const footerStatus=document.querySelector('.footer p:last-child');if(footerStatus)footerStatus.textContent='Operating pilot · simulated capacity where labeled · not an engineering determination';
    const normalizeStageLanguage=root=>{root.querySelectorAll?.('*').forEach(el=>{if(el.children.length)return;const text=(el.textContent||'').trim();if(text.length>80)return;if(/^R\s*&\s*D$/i.test(text)||/^research\s*(?:&|and)\s*development$/i.test(text))el.textContent='OPERATING PILOT';})};normalizeStageLanguage(document.body);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)normalizeStageLanguage(node)}))).observe(document.body,{childList:true,subtree:true});
    const syncNetwork=()=>{document.documentElement.dataset.network=navigator.onLine?'online':'offline';if(networkNote)networkNote.textContent=navigator.onLine?'':' · OFFLINE: LIVE EVIDENCE MAY BE UNAVAILABLE'};syncNetwork();addEventListener('online',syncNetwork);addEventListener('offline',syncNetwork);
    const draftIds=['projectType','siteSelect','powerReq','waterReq','wasteReq','gasReq','fiberReq','timeline','powerRedundancy','risk','growth','capitalExposure'];
    try{const saved=JSON.parse(localStorage.getItem('gage-grid-project-draft-v1')||'null');if(saved?.draft&&Date.now()-Number(saved.savedAt||0)<1000*60*60*24*14)draftIds.forEach(id=>{const el=document.getElementById(id);if(el&&saved.draft[id]!==undefined&&saved.draft[id]!=='')el.value=saved.draft[id]})}catch{}
    const saveDraft=()=>{const draft=Object.fromEntries(draftIds.map(id=>[id,document.getElementById(id)?.value??'']));localStorage.setItem('gage-grid-project-draft-v1',JSON.stringify({savedAt:Date.now(),draft}))};draftIds.forEach(id=>document.getElementById(id)?.addEventListener('change',saveDraft));draftIds.forEach(id=>document.getElementById(id)?.addEventListener('input',saveDraft));
    const advanced=document.querySelector('details.advanced');if(advanced){advanced.open=localStorage.getItem('gage-grid-advanced-open')==='1';advanced.addEventListener('toggle',()=>localStorage.setItem('gage-grid-advanced-open',advanced.open?'1':'0'))}
    const analyse=document.getElementById('analyseBtn');addEventListener('keydown',event=>{const tag=document.activeElement?.tagName;if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(tag)){event.preventDefault();document.getElementById('regSearch')?.focus()}if(event.key==='Escape'){const dialog=document.getElementById('recordDialog');if(dialog?.open)dialog.close()}if((event.metaKey||event.ctrlKey)&&event.key==='Enter'&&tag!=='TEXTAREA'){event.preventDefault();analyse?.click()}});
    analyse?.addEventListener('click',()=>{const original=analyse.textContent;analyse.setAttribute('aria-busy','true');analyse.textContent='RUNNING SITE FEASIBILITY…';setTimeout(()=>{analyse.removeAttribute('aria-busy');analyse.textContent=original},900)});
    const accessForm=document.getElementById('accessForm');accessForm?.addEventListener('submit',()=>{const submit=accessForm.querySelector('button[type="submit"],button:not([type])');if(!submit)return;submit.disabled=true;submit.setAttribute('aria-busy','true');setTimeout(()=>{submit.disabled=false;submit.removeAttribute('aria-busy')},1400)});
    document.querySelectorAll('.inputs input[type="number"]').forEach(input=>{const syncValidity=()=>input.setAttribute('aria-invalid',input.checkValidity()?'false':'true');input.addEventListener('input',syncValidity);syncValidity()});
    const projectType=document.getElementById('projectType');const sharedProject=new URL(location.href).searchParams.get('project');if(projectType&&sharedProject&&[...projectType.options].some(o=>o.value===sharedProject))projectType.value=sharedProject;projectType?.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('project',projectType.value);history.replaceState(null,'',url)});
    const siteSelect=document.getElementById('siteSelect');const sharedSite=new URL(location.href).searchParams.get('site');const restoreSharedSite=()=>{if(siteSelect&&sharedSite&&[...siteSelect.options].some(o=>o.value===sharedSite))siteSelect.value=sharedSite};restoreSharedSite();requestAnimationFrame(restoreSharedSite);siteSelect?.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('site',siteSelect.value);history.replaceState(null,'',url)});
    const baseTitle='Gage Grid — Industrial Site Capacity Intelligence';const syncTitle=()=>{const label=siteSelect?.selectedOptions?.[0]?.textContent?.trim();document.title=label?`${label} | Gage Grid`:baseTitle};syncTitle();requestAnimationFrame(syncTitle);siteSelect?.addEventListener('change',syncTitle);
    const resultState=document.getElementById('resultState');if(resultState){new MutationObserver(()=>{if(!resultState.classList.contains('hidden')&&resultState.children.length&&!resultState.querySelector('[data-screened-at]')){const stamp=document.createElement('div');stamp.dataset.screenedAt='true';stamp.className='preset-note';stamp.textContent=`Screen refreshed ${new Date().toLocaleString()}`;resultState.appendChild(stamp)}}).observe(resultState,{childList:true,subtree:false})}
    const rows=document.getElementById('rows'),exportRegistry=document.getElementById('exportRegistryBtn');const syncExport=()=>{if(exportRegistry)exportRegistry.disabled=!rows?.querySelector('tr')};if(rows){new MutationObserver(syncExport).observe(rows,{childList:true});syncExport()}
    const heroActions=document.querySelector('.hero-actions');if(heroActions&&!document.querySelector('[data-copy-scenario]')){const copy=document.createElement('button');copy.type='button';copy.className='btn ghost';copy.dataset.copyScenario='true';copy.textContent='Copy scenario link';copy.addEventListener('click',async()=>{const url=new URL(location.href);if(projectType?.value)url.searchParams.set('project',projectType.value);if(siteSelect?.value)url.searchParams.set('site',siteSelect.value);try{await navigator.clipboard.writeText(url.toString());copy.textContent='Link copied';setTimeout(()=>copy.textContent='Copy scenario link',1200)}catch{copy.textContent='Copy unavailable'}});heroActions.appendChild(copy)}
  });
})();
