(() => {
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
  ready(()=>{
    const ribbon=document.querySelector('.ribbon');let networkNote=document.querySelector('[data-network-note]');if(!networkNote&&ribbon){networkNote=document.createElement('span');networkNote.dataset.networkNote='true';ribbon.appendChild(networkNote)}
    if(ribbon&&ribbon.firstChild?.nodeType===Node.TEXT_NODE)ribbon.firstChild.textContent='OPERATING PILOT · SIMULATED CAPACITY WHERE LABELED · LIVE PUBLIC EVIDENCE WHERE LABELED · UTILITY VERIFICATION REQUIRED';
    const savedCopy=document.querySelector('.saved-section .head>p');if(savedCopy)savedCopy.textContent='Saved screens stay in this browser for the operating pilot. Revisit a decision without rerunning the same analysis from scratch.';
    const footerStatus=document.querySelector('.footer p:last-child');if(footerStatus)footerStatus.textContent='Operating pilot · simulated capacity where labeled · not an engineering determination';
    const footerIdentity=document.querySelector('.footer p:nth-child(2)');if(footerIdentity)footerIdentity.innerHTML='Industrial infrastructure decision intelligence · <a data-qc-owner="true" href="https://www.queenancapital.com/company" target="_blank" rel="noreferrer">A Queenan Capital company</a>';
    const primaryNav=document.querySelector('.top nav');if(primaryNav){const registry=primaryNav.querySelector('a[href="#registry"]');if(registry)registry.textContent='Evidence';primaryNav.querySelectorAll('a[href="#changes"],a[href="#method"]').forEach(link=>link.remove())}
    const normalizeStageLanguage=root=>{root.querySelectorAll?.('*').forEach(el=>{if(el.children.length)return;const text=(el.textContent||'').trim();if(text.length>80)return;if(/^R\s*&\s*D$/i.test(text)||/^research\s*(?:&|and)\s*development$/i.test(text))el.textContent='OPERATING PILOT';})};normalizeStageLanguage(document.body);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)normalizeStageLanguage(node)}))).observe(document.body,{childList:true,subtree:true});
    const syncNetwork=()=>{document.documentElement.dataset.network=navigator.onLine?'online':'offline';if(networkNote)networkNote.textContent=navigator.onLine?'':' · OFFLINE: LIVE EVIDENCE MAY BE UNAVAILABLE'};syncNetwork();addEventListener('online',syncNetwork);addEventListener('offline',syncNetwork);
    const draftIds=['projectType','siteSelect','powerReq','waterReq','wasteReq','gasReq','fiberReq','timeline','powerRedundancy','risk','growth','capitalExposure'];
    try{const saved=JSON.parse(localStorage.getItem('gage-grid-project-draft-v1')||'null');if(saved?.draft&&Date.now()-Number(saved.savedAt||0)<1000*60*60*24*14)draftIds.forEach(id=>{const el=document.getElementById(id);if(el&&saved.draft[id]!==undefined&&saved.draft[id]!=='')el.value=saved.draft[id]})}catch{}
    const saveDraft=()=>{const draft=Object.fromEntries(draftIds.map(id=>[id,document.getElementById(id)?.value??'']));localStorage.setItem('gage-grid-project-draft-v1',JSON.stringify({savedAt:Date.now(),draft}))};draftIds.forEach(id=>document.getElementById(id)?.addEventListener('change',saveDraft));draftIds.forEach(id=>document.getElementById(id)?.addEventListener('input',saveDraft));
    const advanced=document.querySelector('details.advanced');if(advanced){advanced.open=localStorage.getItem('gage-grid-advanced-open')==='1';advanced.addEventListener('toggle',()=>localStorage.setItem('gage-grid-advanced-open',advanced.open?'1':'0'))}
    const analyse=document.getElementById('analyseBtn');addEventListener('keydown',event=>{const tag=document.activeElement?.tagName;if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(tag)){event.preventDefault();document.getElementById('regSearch')?.focus()}if(event.key==='Escape'){const dialog=document.getElementById('recordDialog');if(dialog?.open)dialog.close()}if((event.metaKey||event.ctrlKey)&&event.key==='Enter'&&tag!=='TEXTAREA'){event.preventDefault();analyse?.click()}});
    analyse?.addEventListener('click',()=>{const original=analyse.textContent;analyse.setAttribute('aria-busy','true');analyse.textContent='RUNNING SITE FEASIBILITY…';setTimeout(()=>{analyse.removeAttribute('aria-busy');analyse.textContent=original},900)});
    const accessForm=document.getElementById('accessForm');accessForm?.addEventListener('submit',()=>{const submit=accessForm.querySelector('button[type="submit"],button:not([type])');if(!submit)return;submit.disabled=true;submit.setAttribute('aria-busy','true');setTimeout(()=>{submit.disabled=false;submit.removeAttribute('aria-busy')},1400)});
    document.querySelectorAll('.inputs input[type="number"]').forEach(input=>{const syncValidity=()=>input.setAttribute('aria-invalid',input.checkValidity()?'false':'true');input.addEventListener('input',syncValidity);syncValidity()});
    const projectType=document.getElementById('projectType');const sharedProject=new URL(location.href).searchParams.get('project');if(projectType&&sharedProject&&[...projectType.options].some(o=>o.value===sharedProject))projectType.value=sharedProject;projectType?.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('project',projectType.value);history.replaceState(null,'',url)});
    const siteSelect=document.getElementById('siteSelect');const sharedSite=new URL(location.href).searchParams.get('site');const restoreSharedSite=()=>{if(siteSelect&&sharedSite&&[...siteSelect.options].some(o=>o.value===sharedSite))siteSelect.value=sharedSite};restoreSharedSite();requestAnimationFrame(restoreSharedSite);siteSelect?.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('site',siteSelect.value);history.replaceState(null,'',url)});
    const baseTitle='Gage Grid — Industrial Site Capacity Intelligence';const syncTitle=()=>{const label=siteSelect?.selectedOptions?.[0]?.textContent?.trim();document.title=label?`${label} | Gage Grid`:baseTitle};syncTitle();requestAnimationFrame(syncTitle);siteSelect?.addEventListener('change',syncTitle);
    const resultState=document.getElementById('resultState');if(resultState){new MutationObserver(()=>{if(!resultState.classList.contains('hidden')&&resultState.children.length&&!resultState.querySelector('[data-screened-at]')){const stamp=document.createElement('div');stamp.dataset.screenedAt='true';stamp.className='preset-note';stamp.textContent=`Screen refreshed ${new Date().toLocaleString()}`;resultState.appendChild(stamp)}}).observe(resultState,{childList:true,subtree:false})}
    const rows=document.getElementById('rows'),exportRegistry=document.getElementById('exportRegistryBtn');const syncExport=()=>{if(exportRegistry)exportRegistry.disabled=!rows?.querySelector('tr')};if(rows){new MutationObserver(syncExport).observe(rows,{childList:true});syncExport()}
    const heroActions=document.querySelector('.hero-actions');if(heroActions&&!document.querySelector('[data-copy-scenario]')){const copy=document.createElement('button');copy.type='button';copy.className='btn ghost';copy.dataset.copyScenario='true';copy.textContent='Copy scenario link';copy.addEventListener('click',async()=>{const url=new URL(location.href);if(projectType?.value)url.searchParams.set('project',projectType.value);if(siteSelect?.value)url.searchParams.set('site',siteSelect.value);try{await navigator.clipboard.writeText(url.toString());copy.textContent='Link copied';setTimeout(()=>copy.textContent='Copy scenario link',1200)}catch{copy.textContent='Copy unavailable'}});heroActions.appendChild(copy)}

    const installWorkedDecision=()=>{
      if(document.getElementById('ggWorkedDecision'))return;
      const metrics=document.querySelector('.mini-metrics');if(!metrics)return;
      const section=document.createElement('section');section.id='ggWorkedDecision';section.className='gg-worked shell';section.innerHTML=`<div class="gg-worked-head"><div><span>WORKED DECISION / ONE CLICK</span><h2>See the screen before you trust the score.</h2><p>Load a 45 MW compute project against the Joliet South pilot node. The capacity result stays explicitly simulated; EPA and USGS context load independently from public sources and never inflate the feasibility score.</p></div><button class="btn" type="button" data-run-worked>RUN WORKED SCREEN →</button></div><div class="gg-worked-grid"><article><span>PROJECT</span><b>45 MW compute</b><small>0.28 MGD water · dual/diverse infrastructure · 24-month target · 20% growth</small></article><article><span>CAPACITY MODEL</span><b>Simulated pilot</b><small>Useful for workflow and diligence ordering. Not a utility commitment.</small></article><article data-epa-card><span>EPA ECHO</span><b>Connecting…</b><small>Live regulated-facility context; independent of the score.</small></article><article data-usgs-card><span>USGS WATER</span><b>Connecting…</b><small>Live nearby gauge context; not municipal service capacity.</small></article></div><div class="gg-worked-rule"><b>THE POINT</b><span>Gage separates three things that are easy to blur together: modeled capacity, live public context, and the site-specific utility confirmation still required before capital is committed.</span></div>`;
      metrics.insertAdjacentElement('afterend',section);
      const style=document.createElement('style');style.id='gg-worked-style';style.textContent=`.gg-worked{margin-top:18px;margin-bottom:30px;border:1px solid #3c4335;background:#151811;padding:22px}.gg-worked-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:end}.gg-worked-head span,.gg-worked-grid span,.gg-worked-rule b{font:800 9px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;color:#caff42}.gg-worked-head h2{margin:7px 0 8px;font-size:clamp(24px,3vw,42px);line-height:.98;color:#f2efe7}.gg-worked-head p{max-width:780px;margin:0;color:#aeb5a7;line-height:1.55}.gg-worked-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:18px}.gg-worked-grid article{min-height:112px;border:1px solid #353b31;background:#10120e;padding:14px}.gg-worked-grid b{display:block;margin:10px 0 6px;font-size:15px;color:#f2efe7}.gg-worked-grid small{display:block;color:#939b8d;line-height:1.45}.gg-worked-grid article[data-live="ok"]{border-color:#55733f}.gg-worked-grid article[data-live="warn"]{border-color:#765f31}.gg-worked-rule{display:flex;gap:18px;margin-top:12px;padding-top:12px;border-top:1px solid #30352c;color:#aeb5a7;font-size:11px;line-height:1.5}.gg-worked-rule b{flex:0 0 auto}.gg-worked .btn{white-space:nowrap}@media(max-width:900px){.gg-worked-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.gg-worked{padding:16px}.gg-worked-head{grid-template-columns:1fr}.gg-worked-head .btn{width:100%}.gg-worked-grid{grid-template-columns:1fr}.gg-worked-rule{display:block}.gg-worked-rule b{display:block;margin-bottom:6px}}`;
      document.head.appendChild(style);
      section.querySelector('[data-run-worked]')?.addEventListener('click',()=>{
        const project=document.getElementById('projectType');if(project){project.value='data';project.dispatchEvent(new Event('change',{bubbles:true}))}
        const values={siteSelect:'GG-IL-101',powerReq:'45',waterReq:'0.28',wasteReq:'0.18',gasReq:'10',fiberReq:'3',powerRedundancy:'3',timeline:'24',risk:'balanced',growth:'20',capitalExposure:'500000'};
        Object.entries(values).forEach(([id,value])=>{const el=document.getElementById(id);if(el){el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}))}});
        document.getElementById('screen')?.scrollIntoView({behavior:'smooth',block:'start'});
        setTimeout(()=>document.getElementById('analyseBtn')?.click(),260);
      });
      const setCard=(selector,status,title,detail)=>{const card=section.querySelector(selector);if(!card)return;card.dataset.live=status;const b=card.querySelector('b'),small=card.querySelector('small');if(b)b.textContent=title;if(small)small.textContent=detail};
      Promise.allSettled([
        fetch('/api/epa-echo?site=GG-IL-101',{headers:{Accept:'application/json'}}).then(r=>r.json()),
        fetch('/api/usgs-water?site=GG-IL-101',{headers:{Accept:'application/json'}}).then(r=>r.json())
      ]).then(([epaResult,usgsResult])=>{
        if(epaResult.status==='fulfilled'&&epaResult.value?.ok){const s=epaResult.value.summary||{};setCard('[data-epa-card]','ok',`${Number(s.regulatedFacilities||0).toLocaleString()} nearby records`,`${s.currentNoncompliance??'—'} current noncompliance · live ECHO context · not capacity evidence`)}else setCard('[data-epa-card]','warn','Live context unavailable','The feasibility model remains available and unchanged.');
        if(usgsResult.status==='fulfilled'&&usgsResult.value?.ok&&usgsResult.value?.nearest){const n=usgsResult.value.nearest;setCard('[data-usgs-card]','ok',`${Number(n.flowCfs).toLocaleString()} cfs observed`,`${n.distanceMiles} mi to ${n.station||'selected gauge'} · ${n.freshnessStatus||'live'} public context`)}else setCard('[data-usgs-card]','warn','Live context unavailable','USGS context is supplemental; it does not establish water serviceability.');
      });
    };
    installWorkedDecision();
  });
})();
