'use strict';
(()=>{
  const files=['54-state-source-registry.js','55-verification-gap.js','56-source-freshness.js','57-requirement-delta.js','58-capital-gate.js','59-shortlist-reason.js','60-confidence-floor.js','61-provenance-export.js','62-mobile-quick-nav.js','63-sprint-accessibility.js','64-scenario-draft.js','65-registry-density.js','66-print-pack.js','67-shortlist-copy.js','68-registry-filter.js'];
  let i=0;
  function next(){if(i>=files.length)return;const file=files[i++];if(document.querySelector(`script[data-gg-sep9="${file}"]`)){next();return}const s=document.createElement('script');s.src=`/upgrades/${file}`;s.dataset.ggSep9=file;s.onload=next;s.onerror=next;document.body.appendChild(s)}
  next();
})();

(()=>{
 const G=window.GGX;if(!G)return;function render(a){if(!a?.rows?.length)return;const anchor=document.getElementById('resultState');if(!anchor)return;let host=document.getElementById('ggConstraintMap');if(!host){host=document.createElement('section');host.id='ggConstraintMap';host.className='gg-constraint-map';anchor.appendChild(host)}const rows=[...a.rows].sort((x,y)=>x.ratio-y.ratio);host.innerHTML=`<div class="gg-cm-head"><div><span>SYSTEM CONSTRAINT MAP</span><strong>${G.esc(a.s?.name||'Selected site')}</strong></div><b>${G.esc(rows[0]?.name||'—')} is the weakest dependency</b></div><div class="gg-cm-grid">${rows.map(r=>{const coverage=Math.max(0,Math.round((Number(r.ratio)||0)*100)),state=coverage<80?'FAIL':coverage<115?'TIGHT':'HEADROOM',w=Math.min(100,coverage);return `<article data-state="${state}"><div><span>${G.esc(r.name)}</span><b>${coverage}%</b></div><div class="gg-cm-track"><i style="width:${w}%"></i><em></em></div><small>${state} · ${r.gap>=0?'+':''}${G.esc(format(r.gap,r.name))} vs requirement</small></article>`}).join('')}</div><p>Bars show risk-adjusted usable capacity as a percentage of the entered requirement. The 100% marker is the modeled coverage threshold—not a utility commitment.</p>`}
 G.injectStyle('gg-constraint-map-css',`.gg-constraint-map{margin:14px 0;padding:14px;border:1px solid #c9d0d5;background:#f7f9fa}.gg-cm-head{display:flex;justify-content:space-between;gap:12px;align-items:end}.gg-cm-head span{font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.09em;color:#2f55d9}.gg-cm-head strong{display:block;margin-top:4px;font-size:15px}.gg-cm-head>b{font-size:10px}.gg-cm-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:11px}.gg-cm-grid article{padding:9px;border:1px solid #d9dee2;background:#fff}.gg-cm-grid article>div:first-child{display:flex;justify-content:space-between;gap:8px;font-size:9px}.gg-cm-track{position:relative;height:7px;margin:7px 0;background:#e6eaed;overflow:hidden}.gg-cm-track i{display:block;height:100%;background:#68727a}.gg-cm-track em{position:absolute;left:99%;top:-2px;width:1px;height:11px;background:#171d22}.gg-cm-grid article[data-state="FAIL"] .gg-cm-track i{background:#b94b3d}.gg-cm-grid article[data-state="TIGHT"] .gg-cm-track i{background:#b1842b}.gg-cm-grid article[data-state="HEADROOM"] .gg-cm-track i{background:#557b5d}.gg-cm-grid small,.gg-constraint-map p{font-size:8px;line-height:1.4;color:#68727a}.gg-constraint-map p{margin:9px 0 0}@media(max-width:720px){.gg-cm-grid{grid-template-columns:1fr 1fr}.gg-cm-head{display:block}.gg-cm-head>b{display:block;margin-top:5px}}`)}G.afterAnalysis(render);
})();